# Generated by Django 2.0 on 2018-06-03 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('userId', models.IntegerField()),
                ('fromBlog', models.CharField(max_length=50, null=True)),
                ('time', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('toUserId', models.IntegerField()),
                ('type', models.CharField(max_length=50)),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='UnreadMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('userId', models.IntegerField()),
                ('fromBlog', models.CharField(max_length=50, null=True)),
                ('time', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('toUserId', models.IntegerField()),
                ('type', models.CharField(max_length=50)),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, unique=True)),
                ('userId', models.IntegerField(unique=True)),
                ('iconUrl', models.URLField(default='/media/head.jpg')),
                ('newlyTime', models.DateField(auto_now=True)),
            ],
        ),
    ]
