# Generated by Django 2.0.5 on 2018-05-07 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, unique=True)),
                ('userId', models.IntegerField(unique=True)),
                ('time', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('toUserId', models.IntegerField()),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UnreadMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, unique=True)),
                ('userId', models.IntegerField(unique=True)),
                ('time', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('toUserId', models.IntegerField()),
                ('type', models.CharField(max_length=50)),
            ],
        ),
    ]
