# Generated by Django 2.0 on 2018-06-24 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='userId',
            field=models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='UserInfo', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='toUser',
            field=models.ForeignKey(db_column='toUser', on_delete=django.db.models.deletion.CASCADE, related_name='ToUser', to='users.UserInfo'),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='user',
            field=models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, related_name='FromUser', to='users.UserInfo'),
        ),
    ]
