# Generated by Django 2.0 on 2018-06-18 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180617_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=30)),
                ('content', models.TextField()),
                ('isRead', models.BooleanField(default=False)),
                ('toUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserInfo')),
            ],
        ),
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msgType', models.CharField(choices=[('LE', 'letter'), ('INT', 'interest')], max_length=20)),
                ('time', models.DateTimeField(auto_now=True)),
                ('isRead', models.BooleanField(default=False)),
                ('content', models.CharField(max_length=200, null=True)),
                ('toUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ToUser', to='users.UserInfo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FromUser', to='users.UserInfo')),
            ],
        ),
    ]
