# Generated by Django 2.0.5 on 2018-05-09 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_message_unreadmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='unreadmessage',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
