# Generated by Django 2.0.5 on 2018-05-09 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180509_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='userId',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='unreadmessage',
            name='userId',
            field=models.IntegerField(),
        ),
    ]
