# Generated by Django 2.0 on 2018-06-19 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_systemmessage_usermessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemmessage',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
