# Generated by Django 2.0.5 on 2018-05-10 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180509_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='fromBlog',
            field=models.IntegerField(blank=True, default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unreadmessage',
            name='fromBlog',
            field=models.IntegerField(blank=True, default=3),
            preserve_default=False,
        ),
    ]
