# Generated by Django 2.0.5 on 2018-05-10 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20180510_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='fromBlog',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='unreadmessage',
            name='fromBlog',
            field=models.IntegerField(null=True),
        ),
    ]
