# Generated by Django 2.0 on 2018-06-26 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20180626_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemmessage',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='newlyTime',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
