# Generated by Django 2.0.5 on 2018-05-15 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20180510_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='link',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unreadmessage',
            name='link',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
