# Generated by Django 2.0 on 2018-07-10 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('blogId', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=50)),
                ('link', models.URLField()),
                ('descript', models.CharField(max_length=100, null=True)),
                ('content', models.TextField()),
                ('readNum', models.IntegerField(default=0)),
                ('time', models.DateTimeField(auto_now=True)),
                ('authorId', models.ForeignKey(db_column='authorId', on_delete=django.db.models.deletion.CASCADE, related_name='userbloglist', to='users.UserInfo')),
            ],
        ),
        migrations.CreateModel(
            name='BlogMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msgType', models.CharField(choices=[('RE', 'reply'), ('CO', 'comment')], max_length=20)),
                ('time', models.DateTimeField(auto_now=True)),
                ('isRead', models.BooleanField(default=False)),
                ('blog', models.ForeignKey(db_column='blog', on_delete=django.db.models.deletion.CASCADE, to='blogs.Blog')),
                ('toUser', models.ForeignKey(db_column='toUser', on_delete=django.db.models.deletion.CASCADE, related_name='BlogtoUser', to='users.UserInfo')),
                ('user', models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, related_name='BlogUser', to='users.UserInfo')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('categoryId', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('commentId', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('name', models.CharField(max_length=50)),
                ('to_blogId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_list', to='blogs.Blog')),
                ('userInfo', models.ForeignKey(db_column='userInfo', on_delete=django.db.models.deletion.CASCADE, related_name='userInfo', to='users.UserInfo')),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('replyId', models.AutoField(primary_key=True, serialize=False)),
                ('to_blogId', models.CharField(max_length=50)),
                ('to_username', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('time', models.DateTimeField(auto_now=True)),
                ('to_commentId', models.ForeignKey(db_column='to_commentId', on_delete=django.db.models.deletion.CASCADE, related_name='reply_list', to='blogs.Comment')),
                ('userInfo', models.ForeignKey(db_column='userInfo', on_delete=django.db.models.deletion.CASCADE, to='users.UserInfo')),
            ],
        ),
        migrations.CreateModel(
            name='testmedel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('content', models.CharField(max_length=50)),
            ],
        ),
    ]
