# Generated by Django 2.0 on 2018-06-21 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('blog_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=50)),
                ('link', models.URLField()),
                ('descript', models.CharField(max_length=100, null=True)),
                ('content', models.TextField()),
                ('readNum', models.IntegerField(default=0)),
                ('time', models.DateTimeField(auto_now=True)),
                ('authorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userbloglist', to='users.UserInfo')),
            ],
        ),
        migrations.CreateModel(
            name='BlogMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msgType', models.CharField(choices=[('RE', 'reply'), ('CO', 'comment')], max_length=20)),
                ('time', models.DateTimeField(auto_now=True)),
                ('isRead', models.BooleanField(default=False)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.Blog')),
                ('toUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BlogtoUser', to='users.UserInfo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BlogUser', to='users.UserInfo')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('to_blogId', models.CharField(max_length=50)),
                ('time', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('name', models.CharField(max_length=50)),
                ('userInfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userInfo', to='users.UserInfo')),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('reply_id', models.AutoField(primary_key=True, serialize=False)),
                ('to_blogId', models.CharField(max_length=50)),
                ('to_username', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('time', models.DateTimeField(auto_now=True)),
                ('to_commentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply_list', to='blogs.Comment')),
                ('userInfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserInfo')),
            ],
        ),
        migrations.CreateModel(
            name='testmedel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('content', models.CharField(max_length=50)),
            ],
        ),
    ]
