# Generated by Django 2.0 on 2018-06-12 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='userid',
        ),
        migrations.AddField(
            model_name='reply',
            name='userInfo',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='users.UserInfo'),
            preserve_default=False,
        ),
    ]
