# Generated by Django 2.0 on 2018-06-18 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180617_1546'),
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msgType', models.CharField(choices=[('RE', 'reply'), ('CO', 'comment')], max_length=20)),
                ('time', models.DateTimeField(auto_now=True)),
                ('isRead', models.BooleanField(default=False)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.Blog')),
                ('toUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BlogtoUser', to='users.UserInfo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BlogUser', to='users.UserInfo')),
            ],
        ),
    ]
