# Generated by Django 2.0 on 2018-06-03 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='to_blogId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.Comment'),
        ),
    ]
