# Generated by Django 2.0 on 2018-06-03 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20180603_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='to_blogId',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='reply',
            name='to_commentId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.Comment'),
        ),
    ]
