# Generated by Django 2.0 on 2018-06-24 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20180624_1141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='reply_id',
            new_name='replyId',
        ),
    ]
