# Generated by Django 2.0 on 2018-06-03 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_auto_20180603_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='to_commentId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply_list', to='blogs.Comment'),
        ),
    ]
