# Generated by Django 2.0 on 2018-06-24 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_auto_20180624_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='to_commentId',
            field=models.ForeignKey(db_column='to_commentId', on_delete=django.db.models.deletion.CASCADE, related_name='reply_list', to='blogs.Comment'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='userInfo',
            field=models.ForeignKey(db_column='userInfo', on_delete=django.db.models.deletion.CASCADE, to='users.UserInfo'),
        ),
    ]
