# Generated by Django 2.0 on 2018-06-24 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_auto_20180624_1151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='blog_id',
            new_name='blogId',
        ),
        migrations.AlterField(
            model_name='blogmessage',
            name='blog',
            field=models.ForeignKey(db_column='blog', on_delete=django.db.models.deletion.CASCADE, to='blogs.Blog'),
        ),
        migrations.AlterField(
            model_name='blogmessage',
            name='toUser',
            field=models.ForeignKey(db_column='toUser', on_delete=django.db.models.deletion.CASCADE, related_name='BlogtoUser', to='users.UserInfo'),
        ),
        migrations.AlterField(
            model_name='blogmessage',
            name='user',
            field=models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, related_name='BlogUser', to='users.UserInfo'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='userInfo',
            field=models.ForeignKey(db_column='userInfo', on_delete=django.db.models.deletion.CASCADE, related_name='userInfo', to='users.UserInfo'),
        ),
    ]
