# Generated by Django 2.0 on 2018-07-11 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_auto_20180710_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='value',
            field=models.CharField(default='ee', max_length=100),
            preserve_default=False,
        ),
    ]
