# Generated by Django 2.0 on 2018-06-26 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_auto_20180624_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='to_blogId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_list', to='blogs.Blog'),
        ),
    ]
