# Generated by Django 2.0 on 2018-08-21 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_auto_20180818_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='userInfo',
            field=models.ForeignKey(db_column='userInfo', on_delete=django.db.models.deletion.CASCADE, related_name='userComment', to='users.UserInfo'),
        ),
    ]
