# Generated by Django 2.0.2 on 2018-02-25 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(default='', max_length=50, unique=True)),
                ('userid', models.IntegerField(default=0, unique=True)),
                ('headlink', models.CharField(default='ssdasdasda', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('blog_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=50)),
                ('link', models.URLField()),
                ('descript', models.CharField(max_length=100, null=True)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('to_blogId', models.IntegerField()),
                ('time', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('username', models.CharField(max_length=20)),
                ('headimg', models.CharField(max_length=50)),
                ('test', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('reply_id', models.AutoField(primary_key=True, serialize=False)),
                ('to_commentId', models.IntegerField()),
                ('username', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('time', models.DateTimeField(auto_now=True)),
                ('headimg', models.CharField(max_length=50)),
                ('to', models.CharField(max_length=20)),
            ],
        ),
    ]
