# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-24 07:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='author',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
