# Generated by Django 2.0.2 on 2018-02-25 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='test',
            field=models.CharField(default='ddd', max_length=100),
            preserve_default=False,
        ),
    ]
