# Generated by Django 2.0.2 on 2018-02-23 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_blog_commemt_myuser_reply_test_test1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test',
        ),
        migrations.DeleteModel(
            name='test1',
        ),
    ]
