# Generated by Django 2.0.2 on 2018-02-12 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_blog_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='testmedel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t', models.CharField(max_length=50)),
                ('link', models.URLField()),
                ('content', models.TextField()),
            ],
        ),
    ]
