# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-24 13:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_blog_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='userid',
            new_name='userId',
        ),
    ]
