# Generated by Django 2.0 on 2018-06-15 02:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='interest',
            unique_together={('user', 'toUserId')},
        ),
    ]
