# Generated by Django 2.0 on 2018-06-24 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_auto_20180621_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, related_name='favo_list', to='users.UserInfo'),
        ),
        migrations.AlterField(
            model_name='interest',
            name='toUserId',
            field=models.ForeignKey(db_column='toUserId', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='interest',
            name='user',
            field=models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, related_name='inter_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
