# Generated by Django 2.0 on 2018-07-06 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_auto_20180706_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='blogId',
            field=models.ForeignKey(db_column='blogId', on_delete=django.db.models.deletion.CASCADE, to='blogs.Blog'),
        ),
    ]
