# Generated by Django 2.0 on 2018-06-18 05:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0003_auto_20180617_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmessage',
            name='toUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BlogtoUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blogmessage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BlogUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='toUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ToUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FromUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
