# Generated by Django 2.0 on 2018-07-08 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0004_auto_20180706_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
