# Generated by Django 2.0 on 2018-06-18 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0005_auto_20180618_1353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogmessage',
            name='blog',
        ),
        migrations.RemoveField(
            model_name='blogmessage',
            name='toUser',
        ),
        migrations.RemoveField(
            model_name='blogmessage',
            name='user',
        ),
        migrations.DeleteModel(
            name='BlogMessage',
        ),
    ]
