# Generated by Django 2.0 on 2018-07-08 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0005_auto_20180708_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='interest',
            name='lastCheckTime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='interest',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
