# Generated by Django 2.0 on 2018-06-18 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0006_auto_20180618_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemmessage',
            name='toUser',
        ),
        migrations.RemoveField(
            model_name='usermessage',
            name='toUser',
        ),
        migrations.RemoveField(
            model_name='usermessage',
            name='user',
        ),
        migrations.DeleteModel(
            name='SystemMessage',
        ),
        migrations.DeleteModel(
            name='UserMessage',
        ),
    ]
