# Generated by Django 2.0 on 2018-06-18 06:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0007_auto_20180618_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='toUserId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='interest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inter_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
